name: PR Validation

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality-gates:
    name: Quality Gates
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          if [ -f "pnpm-lock.yaml" ]; then
            pnpm install --frozen-lockfile
          else
            pnpm install
          fi

      - name: Code formatting check
        run: pnpm format:check

      - name: Lint code
        run: pnpm lint

      - name: Type check
        run: npx tsc --noEmit

      - name: Run unit tests
        run: pnpm test --coverage --watchAll=false

      - name: Upload coverage reports
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false

  build-verification:
    name: Build Verification
    runs-on: ubuntu-latest
    needs: quality-gates
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          if [ -f "pnpm-lock.yaml" ]; then
            pnpm install --frozen-lockfile
          else
            pnpm install
          fi

      - name: Build application
        run: pnpm build

      - name: Verify build completed successfully
        run: |
          echo "Build verification completed"
          if [ -f ".next/BUILD_ID" ]; then
            echo "✅ Build ID: $(cat .next/BUILD_ID)"
          else
            echo "❌ Build failed - no BUILD_ID found"
            exit 1
          fi

  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    needs: quality-gates
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          if [ -f "pnpm-lock.yaml" ]; then
            pnpm install --frozen-lockfile
          else
            pnpm install
          fi

      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps

      - name: Build application for E2E tests
        run: |
          echo "Building application for E2E tests..."
          pnpm build

          echo "Verifying build output..."
          ls -la .next/

          if [ -f ".next/BUILD_ID" ]; then
            echo "✅ BUILD_ID found: $(cat .next/BUILD_ID)"
          else
            echo "❌ BUILD_ID not found - build may have failed"
            exit 1
          fi

      - name: Start application in background
        run: |
          echo "Starting Next.js application..."
          echo "Node version: $(node --version)"
          echo "Checking if .next directory exists..."
          ls -la .next/ || echo "No .next directory found"

          # Start the application with explicit port
          PORT=3000 pnpm start &
          APP_PID=$!
          echo $APP_PID > .next_pid
          echo "Started application with PID: $APP_PID"

          # Give it a moment to start
          sleep 5

          # Check if process is still running
          if kill -0 $APP_PID 2>/dev/null; then
            echo "✅ Application process is running"
          else
            echo "❌ Application process died immediately"
            exit 1
          fi

      - name: Wait for application to be ready
        run: |
          echo "Waiting for application to start on http://localhost:3000..."

          # Try a simple curl first to see if anything is listening
          for i in {1..10}; do
            if curl -s http://localhost:3000 >/dev/null 2>&1; then
              echo "✅ Port 3000 is responding"
              break
            fi
            echo "Attempt $i: Port 3000 not responding yet..."
            sleep 2
          done

          # Now use wait-on with more verbose output
          pnpm exec wait-on http://localhost:3000 --timeout 90000 --interval 3000 --verbose || {
            echo "❌ Application failed to start. Checking logs..."
            
            # Check if process is still running
            if [ -f .next_pid ]; then
              APP_PID=$(cat .next_pid)
              if kill -0 $APP_PID 2>/dev/null; then
                echo "Process is still running, but not responding on port 3000"
              else
                echo "Process has died"
              fi
            fi
            
            # Check what's listening on port 3000
            netstat -tlnp | grep :3000 || echo "Nothing listening on port 3000"
            
            # Check system resources
            echo "System resources:"
            free -h
            df -h
            
            exit 1
          }

          echo "✅ Application is ready!"

      - name: Verify application is responding
        run: |
          echo "Testing application health..."
          curl -f http://localhost:3000/api/health || echo "Health endpoint not available"
          curl -I http://localhost:3000 || echo "Root endpoint not available"

      - name: Run E2E tests
        run: |
          echo "Running Playwright E2E tests..."
          echo "Current directory: $(pwd)"
          echo "Available endpoints:"
          curl -s http://localhost:3000/api/health || echo "Health endpoint not available"

          # Run the tests
          pnpm dlx playwright test --reporter=github

      - name: Stop application
        if: always()
        run: |
          if [ -f .next_pid ]; then
            kill $(cat .next_pid) || true
            rm .next_pid
          fi
          # Fallback: kill any remaining Next.js processes
          pkill -f "next start" || true

      - name: Upload E2E test results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: e2e-test-results
          path: test-results/

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: quality-gates
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          if [ -f "pnpm-lock.yaml" ]; then
            pnpm install --frozen-lockfile
          else
            pnpm install
          fi

      - name: Audit dependencies
        run: pnpm audit --audit-level=high
        continue-on-error: true
